package app

/*
const (

	BACK       Card = "BACK"
	CLUB_1     Card = "CLUB_A"
	CLUB_2     Card = "CLUB_2"
	CLUB_3     Card = "CLUB_3"
	CLUB_4     Card = "CLUB_4"
	CLUB_5     Card = "CLUB_5"
	CLUB_6     Card = "CLUB_6"
	CLUB_7     Card = "CLUB_7"
	CLUB_8     Card = "CLUB_8"
	CLUB_9     Card = "CLUB_9"
	CLUB_10    Card = "CLUB_10"
	CLUB_11    Card = "CLUB_JACK"
	CLUB_12    Card = "CLUB_QUEEN"
	CLUB_13    Card = "CLUB_KING"
	DIAMOND_1  Card = "DIAMOND_A"
	DIAMOND_2  Card = "DIAMOND_2"
	DIAMOND_3  Card = "DIAMOND_3"
	DIAMOND_4  Card = "DIAMOND_4"
	DIAMOND_5  Card = "DIAMOND_5"
	DIAMOND_6  Card = "DIAMOND_6"
	DIAMOND_7  Card = "DIAMOND_7"
	DIAMOND_8  Card = "DIAMOND_8"
	DIAMOND_9  Card = "DIAMOND_9"
	DIAMOND_10 Card = "DIAMOND_10"
	DIAMOND_11 Card = "DIAMOND_JACK"
	DIAMOND_12 Card = "DIAMOND_QUEEN"
	DIAMOND_13 Card = "DIAMOND_KING"
	HEART_1    Card = "HEART_A"
	HEART_2    Card = "HEART_2"
	HEART_3    Card = "HEART_3"
	HEART_4    Card = "HEART_4"
	HEART_5    Card = "HEART_5"
	HEART_6    Card = "HEART_6"
	HEART_7    Card = "HEART_7"
	HEART_8    Card = "HEART_8"
	HEART_9    Card = "HEART_9"
	HEART_10   Card = "HEART_10"
	HEART_11   Card = "HEART_JACK"
	HEART_12   Card = "HEART_QUEEN"
	HEART_13   Card = "HEART_KING"
	SPADE_1    Card = "SPADE_A"
	SPADE_2    Card = "SPADE_2"
	SPADE_3    Card = "SPADE_3"
	SPADE_4    Card = "SPADE_4"
	SPADE_5    Card = "SPADE_5"
	SPADE_6    Card = "SPADE_6"
	SPADE_7    Card = "SPADE_7"
	SPADE_8    Card = "SPADE_8"
	SPADE_9    Card = "SPADE_9"
	SPADE_10   Card = "SPADE_10"
	SPADE_11   Card = "SPADE_JACK"
	SPADE_12   Card = "SPADE_QUEEN"
	SPADE_13   Card = "SPADE_KING"

)
*/
type Card string

const (
	BACK       Card = "BACK"
	CLUB_1     Card = "CLUB_A"
	CLUB_2     Card = "CLUB_2"
	CLUB_3     Card = "CLUB_3"
	CLUB_4     Card = "CLUB_4"
	CLUB_5     Card = "CLUB_5"
	CLUB_6     Card = "CLUB_6"
	CLUB_7     Card = "CLUB_7"
	CLUB_8     Card = "CLUB_8"
	CLUB_9     Card = "CLUB_9"
	CLUB_10    Card = "CLUB_10"
	CLUB_11    Card = "CLUB_JACK"
	CLUB_12    Card = "CLUB_QUEEN"
	CLUB_13    Card = "CLUB_KING"
	DIAMOND_1  Card = "DIAMOND_A"
	DIAMOND_2  Card = "DIAMOND_2"
	DIAMOND_3  Card = "DIAMOND_3"
	DIAMOND_4  Card = "DIAMOND_4"
	DIAMOND_5  Card = "DIAMOND_5"
	DIAMOND_6  Card = "DIAMOND_6"
	DIAMOND_7  Card = "DIAMOND_7"
	DIAMOND_8  Card = "DIAMOND_8"
	DIAMOND_9  Card = "DIAMOND_9"
	DIAMOND_10 Card = "DIAMOND_10"
	DIAMOND_11 Card = "DIAMOND_JACK"
	DIAMOND_12 Card = "DIAMOND_QUEEN"
	DIAMOND_13 Card = "DIAMOND_KING"
	HEART_1    Card = "HEART_A"
	HEART_2    Card = "HEART_2"
	HEART_3    Card = "HEART_3"
	HEART_4    Card = "HEART_4"
	HEART_5    Card = "HEART_5"
	HEART_6    Card = "HEART_6"
	HEART_7    Card = "HEART_7"
	HEART_8    Card = "HEART_8"
	HEART_9    Card = "HEART_9"
	HEART_10   Card = "HEART_10"
	HEART_11   Card = "HEART_JACK"
	HEART_12   Card = "HEART_QUEEN"
	HEART_13   Card = "HEART_KING"
	SPADE_1    Card = "SPADE_A"
	SPADE_2    Card = "SPADE_2"
	SPADE_3    Card = "SPADE_3"
	SPADE_4    Card = "SPADE_4"
	SPADE_5    Card = "SPADE_5"
	SPADE_6    Card = "SPADE_6"
	SPADE_7    Card = "SPADE_7"
	SPADE_8    Card = "SPADE_8"
	SPADE_9    Card = "SPADE_9"
	SPADE_10   Card = "SPADE_10"
	SPADE_11   Card = "SPADE_JACK"
	SPADE_12   Card = "SPADE_QUEEN"
	SPADE_13   Card = "SPADE_KING"
)
